### PR TITLE
Added SavedStateHandle in ViewModel to recover save note data 

### PR DESCRIPTION
**Pull request by devmanishpatole**
from process death.

Used  SavedStateHandle state in case of process death to resume the on-going add note operation.

This is my first pull request, please let me know if anything is missing!

### CODE REVIEW

**Comment by PatilShreyas** [comment]
Thanks @devmanishpatole for this PR 😀.

Basically we need to handle process death in notes list screen (NotesFragment). Can you please do that?

**Comment by devmanishpatole** [comment]
Sure @PatilShreyas I will do that, but can you verify the existing save note operation in case of the process death? feel free to give any inputs if required.

**Comment by devmanishpatole** [comment]
Hi @PatilShreyas,

I was looking into handling process death in the notes list screen (NotesFragment).
But even if process death happens in between the on-going load notes operation that the same operation will resume for the next launch. why do we need an explicit process death handling?

My understanding was process death should not hamper user experience where the user has entered details while creating notes, which might be a lot of important data and we should not lose that data in case of process death. (User might not bother to enter all the notes data again)

We should take care of process death into consideration where we have inputs from a user and based on that if we are performing some operation then that should be resumed in case of process death.

Please let me know your thoughts and please help me understand if I am missing anything or any scenario.

Thanks,
Manish Patole.

**Comment by PatilShreyas** [comment]
@devmanishpatole Yes you're right, so we will need to handle it in the notes list fragment, adding new note and note details.

**Comment by PatilShreyas** [comment]
Why this file change is not showing proper difference?

**Comment by devmanishpatole** [comment]
Even I am surprised why diff is not showing correct code changes. Looks like the issue is with GitHub.

**Comment by PatilShreyas** [comment]
@devmanishpatole I've one point here to discuss

In the upcoming version, we are going to add support for offline capability where data will be saved in the database first and then it'll be interacting with the remote layer. In that case, I don't think we need to handle state because we're already persisting data with local storage. Ref: #36

**Comment by devmanishpatole** [comment]
Hi @PatilShreyas 

The changes I made will recover note saving operation from the process death.
Now how we implement offline capability for note saving matters a lot.

1. If we are going to save a note after it is successfully synced with the backend then we need to handle process death because we can miss the user data in case of process death.
2. If we are going to save note locally immediately after the user hits save then probably we don't need to handle process death (considering local saving operation will be quicker) and after saving it locally later we are going to sync with backend.
But we need to consider the corner case when the user puts the application in the background and your local save operation is in the queue and process death happens.

My point is if we are dealing with user inputs we should consider the process death.
If we are going with the above approach [1] then we should have process death recovery capability for all operations for creating a note, see note details, etc.
If we are going with an approach [2] then we can defer the feature for a while.

Please let me know your thoughts If you have some other approach to add offline capability or anything else.

Thanks.
Manish Patole.

**Comment by PatilShreyas** [comment]
Yeah right. I would suggest to just wait for this till we implement offline
feature for this app.

**Comment by PatilShreyas** [comment]
@devmanishpatole #80 is merged in the `master` which adds offline-capability in the application.

**Comment by devmanishpatole** [comment]
@PatilShreyas I will resolve the conflicts and update the PR.

**Comment by PatilShreyas** [comment]
I tested process death in AddNoteFragment and it's working perfectly. You can check.

- Just go to add a new note.
- Write some random title and body.
- Press 🏡 home button.
- In Android Studio, stop process for the app.
- Again launch app from recent apps and you can see Title and note are there as you types earlier.


LiveData used in `ViewModel`s are not storing state of EditText. So I don't think there's need to save state for these operational `LiveData`s

**Comment by devmanishpatole** [comment]
The user should see earlier typed note title and note data, we should store the state of the operation as it will give a seamless user experience to users when they will resume the application use where they left earlier (Even after process death).
Let me know your thoughts.

**Comment by PatilShreyas** [comment]
Yeah sure, We should do that. But I think we would need this in fragment, right? Not in ViewModel. Because ViewModel isn't storing that state

**Comment by devmanishpatole** [comment]
We are not saving anything apart from title and body, just we are resuming the add note operation when the application is relaunched after process death.

**Comment by devmanishpatole** [comment]
I am not getting how to shift that restores state logic into a fragment. 
Additionally, we are driving the UI state changes from ```ViewModel``` only.

**Comment by PatilShreyas** [comment]
Did you tested current application? Now add operation is just completing within second. 

Maybe we'll need to use `savedInstanceState`

**Comment by devmanishpatole** [comment]
Oh, I got it, my understanding was even though we have that implementation is in place still we are going ahead with process death handling in ```ViewModel```. 
As it would be a corner case but I would suggest having that process in place. Because of that, we don't need to determine in which state our UI was when we resume, otherwise, in the case of ```savedInstanceState``` we can only store title and body but couldn't determine the UI state as well as on-going operation.

**Comment by PatilShreyas** [comment]
@devmanishpatole Yeah we just wanted that. That's why I would suggest you please test the current app.

**Comment by PatilShreyas** [comment]
I would recommend you to read this: https://developer.android.com/guide/fragments/saving-state

**Comment by devmanishpatole** [comment]
I have tested the current app, first we store note locally and thanks I will go thourgh the link and will get back.

**Comment by PatilShreyas** [comment]
@devmanishpatole Any update on this? Is it still needed for implementation?

**Comment by PatilShreyas** [comment]
Maybe we can close this as of now. Feel free to contribute again. I would recommend first discuss and then let's raise PR

**Comment by devmanishpatole** [comment]
Sure @PatilShreyas

**Pull request closed without merging**
