### PR TITLE
Adding unit test cases

### PR DESCRIPTION
**Pull request by devmanishpatole**
Adding unit test cases for NoteDetailViewModel.

Achieved 100% test coverage for the class -

image

Added dependency for [MockK](https://mockk.io/)
Unfortunately, GitHub again not showing the changes in the diff, please let me know if I can help you to understand my changes.

### CODE REVIEW

**Comment by PatilShreyas** [comment]
@devmanishpatole thanks for this PR and contribution.

Actually we wanted to use Kotest framework with BDD pattern. We should have been already discussed this before raising PR.

**Comment by devmanishpatole** [comment]
Got it @PatilShreyas 
You mentioned in the issue -

- Add Unit tests for modules data, repository, ViewModel, etc.
- Add some integrations tests for Android.
- We can use libraries like Kotest, Mockk, etc for testing which are completely Kotlin libraries.

So I went ahead and added a unit test case for ViewModel using Mockk.

Do you want me to cancel the pull request?

**Comment by PatilShreyas** [comment]
Yeah that would be helpful. Because I've planned something which we can discuss first on issue

**Comment by PatilShreyas** [comment]
@devmanishpatole Also make sure that there are so many changes that will be going to happen in this app. So many code changes will be there as well. So please wait for some time with the tests as it's not at high priority as of now.

**Pull request closed without merging**
