### PR TITLE
[ComposeApp] Improve UI for dark mode

### LINKED ISSUE #282: About page - Shadow cutting of visit card
Shadow is cutting from bottom in Visit card

### LINKED ISSUE #286: Dark mode Improvements

### PR DESCRIPTION
**Pull request by yogeshpaliyal**
## Summary
1. Dark mode improvements in Login and Signup
2. Fix Clipping of Card Shadow in About page

## A picture or screenshot regarding change

image

image

image

## Checklist

- [x] Build and linting is passing.
- [x] This change is not breaking existing flow of a system.
- [ ] I have written test case for this change. (not required)
- [x] This change is tested from all aspects.
- [ ] Implemented any new third-party library _(Which not existed before this change)_.

closes #282 , closes #286

### CODE REVIEW

**Comment by yogeshpaliyal** [comment]
@PatilShreyas can you have a look?

**Review by PatilShreyas — APPROVED** [review]
Nice @yogeshpaliyal, LGTM 😃. Merging it... 🚀

**Comment by PatilShreyas** [comment]
Waiting for CI to run successful

**Comment by PatilShreyas** [comment]
If you are doing this for hacktoberfest, then adding a label as well.

**Comment by yogeshpaliyal** [comment]
Not just for hacktoberfest, thanks

**Pull request merged**
