### PR TITLE
refactored all Gradle scripts to Kotlin, updated dependencies closes #124

### LINKED ISSUE #124: [API] Update gradle to 6.8.2, refactor gradle scripts to Kotlin, update Kotlin & Ktor
None of this is really necessary but I enjoyed doing it :)

Submitting PR

Thanks!

-Alexi

### PR DESCRIPTION
**Pull request by ruffCode**
I updated Gradle to 6.8.2 and refactored all scripts. Everything seems to be working, all tests pass.

Thanks!

-Alex

closes  #124

### CODE REVIEW

**Comment by ruffCode** [comment]
The automated build is failing due to a syntax error in settings.gradle.kts. This may just be because the github build is using an old version of gradle (6.1.1). I'll try to fix this.

**Comment by PatilShreyas** [comment]
Thanks, @ruffCode for this change. Really appreciable. But I'm not thinking of using `.kts` for this project yet.

**Comment by StylianosGakis** [comment]
> Thanks, @ruffCode for this change. Really appreciable. But I'm not thinking of using `.kts` for this project yet.

It would be interesting to at least have a separate branch that contains the '.kts' version just for those of us who may be interested in seeing this alternative. Here as a PR people are more likely to miss it.

Do you think this is something that could be done or would it be not optimal for you to maintain the separate branch in case of changes, or to have to explain that the '.kts' branch is just there as an example and will not be getting updates?

I would personally be really happy to be able to look at this as a separate branch.

**Comment by PatilShreyas** [comment]
@StylianosGakis @ruffCode Currently it's out of the plan so closing it. Please have a discussion on issues or discussion section before actually raising PR. Please read the contribution guidelines as well.

**Pull request closed without merging**
